#!/bin/sh

# downloaded from docker-library/php
# https://github.com/docker-library/php/tree/fa6464a43d74d8b0a5ec3f22d53ac330f63ad22d/7.1

set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php "$@"
fi

exec "$@"
